language: go
sudo: false
go:
- "1.14"

addons:
  apt:
    packages:
      - rpm
install:
- sudo apt-get -y install python-netifaces python-netaddr
script:
- make test
- make
- sudo make integration
#before_deploy:
#- gem install fpm && make packages
#- export RPM_PACKAGE_NAME=$(ls relaymon-*.x86_64.rpm | tail -n1)
#- export DEB_PACKAGE_NAME=$(ls relaymon-*.amd64.deb | tail -n1)
